language: node_js
node_js:
  - "5"
addons:
  hosts:
    - first.server.com
    - second.server.com
script:
  - "sudo $(which npm) test"
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"